name: Run Core Config Map Tests

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-core-config-map-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      
      - name: Skip Tests (No-op)
        run: true
