name: Publish

on:
  push:
    tags:
      - "*.*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          cache-image: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          GIT_TAG=$(git describe --exact-match --abbrev=0 2>/dev/null || echo "latest")
          export IMAGE=ghcr.io/kubeobj/noobaa-operator:$GIT_TAG
          export CATALOG_IMAGE=ghcr.io/kubeobj/noobaa-operator-catalog:$GIT_TAG
          export CONTAINER_IMAGE_BUILDER_ARGS='--push --builder=container --platform=linux/amd64,linux/arm64'

          docker buildx create --name container --driver=docker-container || true
          make
